services:
  web:
    build: .
    image: django-op-backend-image:latest  # Specify your image name
    container_name: django-op-backend-container # Specify your container name
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app  # Mount your application directory to the container
    restart: unless-stopped  # Restart policy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://opapi.techicious.store"]  # Adjust this endpoint
      interval: 30s
      timeout: 10s
      retries: 3